name: 'dbt_athena_poc'
version: '1.0.0'
profile: 'dbt_athena_poc'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_athena_poc:
    +persist_docs:
      relation: true
      columns: true
    sourcing:
      application_data_model:
        +materialized: view
        +tags: ["application_data_model"]
      denormalised_data_model:
        +materialized: incremental
        +table_type: iceberg
        +incremental_strategy: merge
        +on_schema_change: append_new_columns
        +s3_data_naming: table
        +tags: ["denormalised_data_model"]
    kpi:
      oee:
        +materialized: incremental
        +table_type: iceberg
        +incremental_strategy: merge
        +on_schema_change: append_new_columns
        +s3_data_naming: table
        +tags: ["kpi", "oee"]