version: 2

models:
  - name: src_segments
    description: "View on the Iceberg source table: segments."
    columns:
      - name: id
        description: "Primary key for the segment."
        tests:
          - not_null:
              config:
                severity: warn
          - unique:
              config:
                severity: warn

  - name: src_cards
    description: "View on the Iceberg source table: cards."
    columns:
      - name: id
        description: "Primary key for the card."
        tests:
          - not_null:
              config:
                severity: warn
          - unique:
              config:
                severity: warn

  - name: src_card_segment
    description: "View on the Iceberg source table: card_segment (segment-to-card mapping)."
    columns:
      - name: segment_id
        tests:
          - not_null:
              config:
                severity: warn
      - name: card_id
        tests:
          - not_null:
              config:
                severity: warn
